schools/config/routes.rb
Rails.application.routes.draw do
  resources :schools

  root 'schools#index'
  

end

schools/app/models/school.rb
class School < ActiveRecord::Base
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end
  

schools/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

schools/app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]

  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url, notice: 'School was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      params.require(:school).permit(:student, :teacher, :pet, :grade, :avatar)
    end
end

schools/app/helpers/application_helper.rb
module ApplicationHelper
end

schools/app/helpers/schools_helper.rb
module SchoolsHelper
end

schools/app/views/schools/_form.html.erb
<%= form_for(@school) do |f| %>
  <% if @school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% @school.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :student %><br>
    <%= f.text_area :student %>
  </div>
  <div class="field">
    <%= f.label :teacher %><br>
    <%= f.text_area :teacher %>
  </div>
  <div class="field">
    <%= f.label :pet %><br>
    <%= f.check_box :pet %>
  </div>

<div class="field form-group">
    <%= f.label :grade %><br>
    <%= f.number_field :grade, class: "form-control" %>
  </div>

 <div class="field form-group">
    <%= f.label "Photo" %><br>
    <%= f.file_field :avatar %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

schools/app/views/schools/edit.html.erb
<h1>Editing School</h1>

<%= render 'form' %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

schools/app/views/schools/index.html.erb
<p id="notice"><%= notice %></p>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>


<nav class="navbar navbar-default navbar-static-top">  
<div class="container">
<ul class="nav nav-pills">
  
  <li role="presentation" class="disabled"><a href="#">Students</a></li>
    <li role="presentation" class="disabled"><a href="#">Teachers</a></li>
      <li role="presentation" class="disabled"><a href="#">Grades</a></li>
</ul>

  </div>
</nav>

<h1>Classes</h1>
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Classroom Information</div>
  <div class="panel-body">
    <p>Cardigan typewriter meggings YOLO. Aesthetic retro fashion axe, raw denim kitsch cred literally church-key. Irony gluten-free farm-to-table brunch shabby chic. Ethical wayfarers bespoke bitters, slow-carb Odd Future Schlitz squid Wes Anderson umami banh mi. Disrupt mumblecore viral, Odd Future gluten-free sustainable readymade hoodie flannel salvia fixie. Disrupt Portland hella swag Pitchfork paleo. Kitsch synth PBR banh mi gentrify.</p>
  </div>
<div class="container">
<table class="table">
  <thead>
    <tr>
      <th>Student</th>
      <th>Teacher</th>
      <th>Pet</th>
      <th>Grade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schools.each do |school| %>
      <tr>
        <td><%= school.student %><%= image_tag school.avatar.url(:thumb), class: "img-responsive" %></td>
        <td><%= school.teacher %></td>
        <td><%= school.pet %></td>
        <td><%= school.grade %></td>


        <td><%= link_to 'Select', school %></td>
        <td><%= link_to 'Update', edit_school_path(school) %></td>
        <td><%= link_to 'Delete', school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<%= link_to 'Add a Classroom', new_school_path %>

schools/app/views/schools/new.html.erb
<h1>New School</h1>

<%= render 'form' %>

<%= link_to 'Back', schools_path %>

schools/app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student:</strong>
  <%= @school.student %>
</p>

<%= image_tag @school.avatar.url(:thumb) %>

<p>
  <strong>Teacher:</strong>
  <%= @school.teacher %>
</p>

<p>
  <strong>Pet:</strong>
  <%= @school.pet %>
</p>

<p>
  <strong>Grade:</strong>
  <%= @school.grade %>
</p>



<%= link_to 'Edit', edit_school_path(@school) %> |
<%= link_to 'Back', schools_path %>