mayoszn/config/routes.rb
Rails.application.routes.draw do
  
  root 'epicenter#feed'

  get 'user_profile' => 'epicenter#show_user'

  post 'now_following' => 'epicenter#now_following'

  post 'unfollow' => 'epicenter#unfollow'

  get 'js_practice' => 'epicenter#js_practice'

  resources :assists
  devise_for :users
  

end

mayoszn/app/models/assist.rb
class Assist < ActiveRecord::Base
  belongs_to :user

   validates :message, presence: true
  validates :message, length: {maximum: 140, 
too_long: "A tweet is only 140 max. Everybody knows that!"}
end

mayoszn/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :assists

  validates :username, presence: true, uniqueness: true

  serialize :following, Array
  

end

mayoszn/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

   before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters

    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, 
      :name, :username, :bio, :location, :following) }

    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :password_confirmation, 
      :current_password, :name, :username, :bio, :location, :following) }

  end
end

mayoszn/app/controllers/assists_controller.rb
class AssistsController < ApplicationController
  before_action :set_assist, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /assists
  # GET /assists.json
  def index
    @assists = Assist.all
  end

  # GET /assists/1
  # GET /assists/1.json
  def show
  end

  # GET /assists/new
  def new
    @assist = Assist.new
  end

  # GET /assists/1/edit
  def edit
  end

  # POST /assists
  # POST /assists.json
  def create
    @assist = Assist.new(assist_params)

    respond_to do |format|
      if @assist.save
        format.html { redirect_to @assist, notice: 'Assist was successfully created.' }
        format.json { render :show, status: :created, location: @assist }
      else
        format.html { render :new }
        format.json { render json: @assist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assists/1
  # PATCH/PUT /assists/1.json
  def update
    respond_to do |format|
      if @assist.update(assist_params)
        format.html { redirect_to @assist, notice: 'Assist was successfully updated.' }
        format.json { render :show, status: :ok, location: @assist }
      else
        format.html { render :edit }
        format.json { render json: @assist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assists/1
  # DELETE /assists/1.json
  def destroy
    @assist.destroy
    respond_to do |format|
      format.html { redirect_to assists_url, notice: 'Assist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assist
      @assist = Assist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assist_params
      params.require(:assist).permit(:message, :user_id)
    end
end

mayoszn/app/controllers/epicenter_controller.rb
class EpicenterController < ApplicationController
  def feed
  	# array of current user's following list
  	@following_assists = []

  	# all assists
  	@assists = Assist.all

# assists are pushed into the arrary for our following list
  	@assists.each do |assist|
  		current_user.following.each do |f|
  			if assist.user_id == f
  				@following_assists.push(assist)
  			end
  		end
  	end

  end

  def show_user
  	@user = User.find(params[:id])
  end

  def now_following
  	# just for display
  	@user = User.find(params[:follow_id])

  	#for back-end work
  	current_user.following.push(params[:follow_id].to_i)
  	#adding user id of users you want to follow to an array

  	current_user.save
  	#and save in the database

  end

  def unfollow
    @user = User.find(params[:unfollow_id])
    current_user.following.delete(params[:unfollow_id].to_i)
    current_user.save
  end
end

mayoszn/app/helpers/application_helper.rb
module ApplicationHelper
end

mayoszn/app/helpers/assists_helper.rb
module AssistsHelper
end

mayoszn/app/helpers/epicenter_helper.rb
module EpicenterHelper
end

mayoszn/app/views/assists/_form.html.erb
<%= form_for(@assist) do |f| %>
  <% if @assist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@assist.errors.count, "error") %> prohibited this assist from being saved:</h2>

      <ul>
      <% @assist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_field :message %>
  </div>

  <div class="field cant-see-me">
  <%= f.label :user_id%><br>
  <%= f.number_field :user_id, value: current_user.id %>
  </div><br>
  
  <div class="actions">
    <%= f.submit "Assist!"%>
  </div>
<% end %>

mayoszn/app/views/assists/edit.html.erb
<h1>Editing Assist</h1>

<%= render 'form' %>

<%= link_to 'Show', @assist %> |
<%= link_to 'Back', assists_path %>

mayoszn/app/views/assists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Assists</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @assists.each do |assist| %>
      <tr>
        <td><%= assist.message %></td>
        <td><%= link_to assist.user.username, user_profile_path(id: assist.user.id) %></td> 
        <td><%= link_to 'Show', assist %></td>
        <td><%= link_to 'Edit', edit_assist_path(assist) %></td>
        <td><%= link_to 'Destroy', assist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Assist', new_assist_path %>

mayoszn/app/views/assists/new.html.erb
<h1>New Assist</h1>

<%= render 'form' %>

<%= link_to 'Back', assists_path %>

mayoszn/app/views/assists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @assist.message %>
</p>

<p>
  <strong>User:</strong>
<%= @assist.user.username %>
</p>

<%= link_to 'Edit', edit_assist_path(@assist) %> |
<%= link_to 'Back', assists_path %>