iceandfire_app/config/routes.rb
Rails.application.routes.draw do

  root "iceandfires#index"

  resources :iceandfires

end

iceandfire_app/app/models/iceandfire.rb
class Iceandfire < ActiveRecord::Base
end

iceandfire_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

iceandfire_app/app/controllers/iceandfires_controller.rb
class IceandfiresController < ApplicationController
  before_action :set_iceandfire, only: [:show, :edit, :update, :destroy]

  # GET /iceandfires
  # GET /iceandfires.json
  def index
    @iceandfires = Iceandfire.all
  end

  # GET /iceandfires/1
  # GET /iceandfires/1.json
  def show
  end

  # GET /iceandfires/new
  def new
    @iceandfire = Iceandfire.new
  end

  # GET /iceandfires/1/edit
  def edit
  end

  # POST /iceandfires
  # POST /iceandfires.json
  def create
    @iceandfire = Iceandfire.new(iceandfire_params)

    respond_to do |format|
      if @iceandfire.save
        format.html { redirect_to @iceandfire, notice: 'Reading List was successfully created.' }
        format.json { render :show, status: :created, location: @iceandfire }
      else
        format.html { render :new }
        format.json { render json: @iceandfire.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /iceandfires/1
  # PATCH/PUT /iceandfires/1.json
  def update
    respond_to do |format|
      if @iceandfire.update(iceandfire_params)
        format.html { redirect_to @iceandfire, notice: 'Readling List was successfully updated.' }
        format.json { render :show, status: :ok, location: @iceandfire }
      else
        format.html { render :edit }
        format.json { render json: @iceandfire.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /iceandfires/1
  # DELETE /iceandfires/1.json
  def destroy
    @iceandfire.destroy
    respond_to do |format|
      format.html { redirect_to iceandfires_url, notice: 'Readling List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_iceandfire
      @iceandfire = Iceandfire.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def iceandfire_params
      params.require(:iceandfire).permit(:title, :book, :purchased, :pages, :current, :page, :finish)
    end
end

iceandfire_app/app/helpers/application_helper.rb
module ApplicationHelper
end

iceandfire_app/app/helpers/iceandfires_helper.rb
module IceandfiresHelper
end

iceandfire_app/app/views/iceandfires/_form.html.erb
<%= form_for(@iceandfire) do |f| %>
  <% if @iceandfire.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@iceandfire.errors.count, "error") %> prohibited this iceandfire from being saved:</h2>

      <ul>
      <% @iceandfire.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

     <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :purchased %><br>
    <%= f.check_box :purchased %>
  </div>
  <div class="field">
    <%= f.label :Total_Pages %><br>
    <%= f.number_field :pages %>
  </div>

  <div class="field">
    <%= f.label :current_Page %><br>
    <%= f.number_field :page %>
  </div>
  <div class="field">
    <%= f.label :Finish_By %><br>
    <%= f.date_select :finish %>
  </div>
  <div class="action">
    <%= f.submit %>
  </div>
<% end %>

iceandfire_app/app/views/iceandfires/edit.html.erb
<h1>Editing Iceandfire</h1>

<%= render 'form' %>

<%= link_to 'Show', @iceandfire %> |
<%= link_to 'Back', iceandfires_path %>

iceandfire_app/app/views/iceandfires/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reading List: A Song of Ice and Fire</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Purchased</th>
      <th>Pages</th>
      <th>Current Page</th>
      <th>Finish</th>
      <th colspan="12"></th>
    </tr>
  </thead>

  <tbody>
    <% @iceandfires.each do |iceandfire| %>
      <tr>
        <td><%= iceandfire.title %></td>
        <td><%= iceandfire.description %></td>
        <td><%= iceandfire.purchased %></td>
        <td><%= iceandfire.pages %></td>
        <td><%= iceandfire.current %></td>
        <td><%= iceandfire.finish %></td>
        <td><%= link_to 'Select', iceandfire %></td>
        <td><%= link_to 'Update', edit_iceandfire_path(iceandfire) %></td>
        <td><%= link_to 'Delete', iceandfire, method: :delete, data: { confirm: 'Really? Trash it?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add Book', new_iceandfire_path %>

iceandfire_app/app/views/iceandfires/new.html.erb
<h1>Add a Book</h1>

<%= render 'form' %>

<%= link_to 'Back', iceandfires_path %>

iceandfire_app/app/views/iceandfires/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @iceandfire.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @iceandfire.description %>
</p>


<p>
  <strong>Book:</strong>
  <%= @iceandfire.book %>
</p>

<p>
  <strong>Purchased:</strong>
  <%= @iceandfire.purchased %>
</p>

<p>
  <strong>Total Pages:</strong>
  <%= @iceandfire.pages %>
</p>

<p>
  <strong>Current:</strong>
  <%= @iceandfire.current %>
</p>


<p>
  <strong>Finish:</strong>
  <%= @iceandfire.finish %>
</p>

<%= link_to 'Edit', edit_iceandfire_path(@iceandfire) %> |
<%= link_to 'Back', iceandfires_path %>