roomclass/config/routes.rb
Rails.application.routes.draw do

  resources :roomclasses
  root 'roomclasses#index'
  
get 'about' => 'welcome#about'
  

end

roomclass/app/models/roomclass.rb
class Roomclass < ActiveRecord::Base
end

roomclass/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

roomclass/app/controllers/roomclasses_controller.rb
class RoomclassesController < ApplicationController
  before_action :set_roomclass, only: [:show, :edit, :update, :destroy]

  def index
    @roomclasses = Roomclass.all
  end

  # GET /roomclasses/1
  # GET /roomclasses/1.json
  def show
  end

  # GET /roomclasses/new
  def new
    @roomclass = Roomclass.new
  end

  # GET /roomclasses/1/edit
  def edit
  end

  # POST /roomclasses
  # POST /roomclasses.json
  def create
    @roomclass = Roomclass.new(roomclass_params)

    respond_to do |format|
      if @roomclass.save
        format.html { redirect_to @roomclass, notice: 'Roomclass was successfully created.' }
        format.json { render :show, status: :created, location: @roomclass }
      else
        format.html { render :new }
        format.json { render json: @roomclass.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roomclasses/1
  # PATCH/PUT /roomclasses/1.json
  def update
    respond_to do |format|
      if @roomclass.update(roomclass_params)
        format.html { redirect_to @roomclass, notice: 'Roomclass was successfully updated.' }
        format.json { render :show, status: :ok, location: @roomclass }
      else
        format.html { render :edit }
        format.json { render json: @roomclass.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roomclasses/1
  # DELETE /roomclasses/1.json
  def destroy
    @roomclass.destroy
    respond_to do |format|
      format.html { redirect_to roomclasses_url, notice: 'Roomclass was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_roomclass
      @roomclass = Roomclass.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def roomclass_params
      params.require(:roomclass).permit(:student, :teacher, :pet)
    end
end

roomclass/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

end

roomclass/app/helpers/application_helper.rb
module ApplicationHelper
end

roomclass/app/helpers/roomclasses_helper.rb
module RoomclassesHelper
end

roomclass/app/helpers/welcome_helper.rb
module WelcomeHelper
end

roomclass/app/views/roomclasses/_form.html.erb
<%= form_for(@roomclass) do |f| %>
  <% if @roomclass.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@roomclass.errors.count, "error") %> prohibited this roomclass from being saved:</h2>

      <ul>
      <% @roomclass.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :student %><br>
    <%= f.text_field :student %>
  </div>
  <div class="field">
    <%= f.label :teacher %><br>
    <%= f.text_area :teacher %>
  </div>
  <div class="field">
    <%= f.label :pet %><br>
    <%= f.text_area :pet %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

roomclass/app/views/roomclasses/edit.html.erb
<h1>Editing Roomclass</h1>

<%= render 'form' %>

<%= link_to 'Show', @roomclass %> |
<%= link_to 'Back', roomclasses_path %>

roomclass/app/views/roomclasses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Roomclasses</h1>

<table>
  <thead>
    <tr>
      <th>Student</th>
      <th>Teacher</th>
      <th>Pet</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= @roomclasses.each do |roomclass| %>
      <tr>
        <td><%= roomclass.student %></td>
        <td><%= roomclass.teacher %></td>
        <td><%= roomclass.pet %></td>

        <td><%= link_to 'Show', roomclass %></td>
        <td><%= link_to 'Edit', edit_roomclass_path(roomclass) %></td>
        <td><%= link_to 'Destroy', roomclass, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Roomclass', new_roomclass_path %>

roomclass/app/views/roomclasses/new.html.erb
<h1>New Roomclass</h1>

<%= render 'form' %>

<%= link_to 'Back', roomclasses_path %>

roomclass/app/views/roomclasses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student:</strong>
  <%= @roomclass.student %>
</p>

<p>
  <strong>Teacher:</strong>
  <%= @roomclass.teacher %>
</p>

<p>
  <strong>Pet:</strong>
  <%= @roomclass.pet %>
</p>




<%= link_to 'Edit', edit_roomclass_path(@roomclass) %> |
<%= link_to 'Back', roomclasses_path %>

roomclass/app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

roomclass/app/views/welcome/index.html.erb
<html>
<head>
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>